name: Continuous integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * *'
jobs:
  Runner-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 14, 16, 18 ]
    steps:
    - name: Checkout Git Source
      uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Npm && wrk
      run: npm i -g npm@8 && sudo apt install -y wrk

    - name: Install Dependencies
      run: npm i && npx lerna bootstrap --no-ci

    - name: Continuous integration
      run: sh wrk.sh
